USE [master]
GO
/****** Object:  Database [qlTin]    Script Date: 7/13/2020 11:10:30 PM ******/
CREATE DATABASE [qlTin]
 GO
ALTER DATABASE [qlTin] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [qlTin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [qlTin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [qlTin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [qlTin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [qlTin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [qlTin] SET ARITHABORT OFF 
GO
ALTER DATABASE [qlTin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [qlTin] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [qlTin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [qlTin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [qlTin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [qlTin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [qlTin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [qlTin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [qlTin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [qlTin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [qlTin] SET  DISABLE_BROKER 
GO
ALTER DATABASE [qlTin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [qlTin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [qlTin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [qlTin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [qlTin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [qlTin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [qlTin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [qlTin] SET RECOVERY FULL 
GO
ALTER DATABASE [qlTin] SET  MULTI_USER 
GO
ALTER DATABASE [qlTin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [qlTin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [qlTin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [qlTin] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'qlTin', N'ON'
GO
USE [qlTin]
GO
/****** Object:  Table [dbo].[Theloaitin]    Script Date: 7/13/2020 11:10:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Theloaitin](
	[IDLoai] [int] NOT NULL,
	[Tentheloai] [nvarchar](max) NULL,
 CONSTRAINT [PK_Theloaitin] PRIMARY KEY CLUSTERED 
(
	[IDLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Tintuc]    Script Date: 7/13/2020 11:10:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tintuc](
	[IDTin] [int] NOT NULL,
	[idLoai] [int] NULL,
	[Tieudetin] [nvarchar](max) NULL,
	[Noidungtin] [ntext] NULL,
 CONSTRAINT [PK_Tintuc] PRIMARY KEY CLUSTERED 
(
	[IDTin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
INSERT [dbo].[Theloaitin] ([IDLoai], [Tentheloai]) VALUES (1, N'Thể thao')
INSERT [dbo].[Theloaitin] ([IDLoai], [Tentheloai]) VALUES (2, N'Chính trị')
INSERT [dbo].[Theloaitin] ([IDLoai], [Tentheloai]) VALUES (3, N'Thế giới')
INSERT [dbo].[Tintuc] ([IDTin], [idLoai], [Tieudetin], [Noidungtin]) VALUES (1, 2, N'Khủng hoảng kinh tế trong năm 2012', N'Tình hình khủng hoảng kinh tế năm 2012 được các chuyên gia kinh tế đánh gia')
INSERT [dbo].[Tintuc] ([IDTin], [idLoai], [Tieudetin], [Noidungtin]) VALUES (2, 1, N'Tranh chấp trên biển đông', N'Trên các diễn đàn quân sự đang nóng dần về tình hình biển đông')
ALTER TABLE [dbo].[Tintuc]  WITH CHECK ADD  CONSTRAINT [FK_Tintuc_Theloaitin] FOREIGN KEY([idLoai])
REFERENCES [dbo].[Theloaitin] ([IDLoai])
GO
ALTER TABLE [dbo].[Tintuc] CHECK CONSTRAINT [FK_Tintuc_Theloaitin]
GO
USE [master]
GO
ALTER DATABASE [qlTin] SET  READ_WRITE 
GO
